language: node_js
node_js:
  - lts/*
before_install:
  #  - bash script/zip_lambda.sh
  - bash script/create_aws_profile.sh
install:
  - npm ci
script:
  - npm test
  - npm run build
after_script:
  - cdk diff
after_success:
  - cdk synth
before_deploy:
  - cdk bootstrap aws://${AWS_ACCOUNT_ID}/${AWS_REGION}
deploy:
  provider: script
  script: cdk deploy --all --require-approval "never"
  on:
    branch: main