language: node_js
node_js:
  - lts/*
#before_install:
#  - bash script/zip_lambda.sh
install:
  - npm ci
script:
  - npm test
  - npm run build
after_script:
  - cdk diff
after_success:
  - cdk synth
#deploy:
#  provider: script
#  script: cdk deploy
#  on:
#    branch: main