name: AWS CDK CI - PUSH

on:
  push:
    branches:
      - "**"
    paths:
      - "**.ts"
      - ".github/workflows/push.yml"
      - "**.json"
      - "**.yaml"

env:
  GITHUB_OAUTH_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
  WEBSITE_DEV_PASS: ${{ secrets.WEBSITE_DEV_PASS }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  COGNITO_AFFILIATE_REGION: ${{ secrets.COGNITO_AFFILIATE_REGION }}
  AWS_USER_POOL_ID: ${{secrets.AWS_USER_POOL_ID}}
  GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
  GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  GOOGLE_API_SERVICE_ACCOUNT_INFO: ${{ secrets.GOOGLE_API_SERVICE_ACCOUNT_INFO }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
  SLACK_WORKSPACE_ID: ${{ secrets.SLACK_WORKSPACE_ID }}
  BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DEPLOY_KEY: ${{ secrets.FEEDS_DEPLOY_PRIVATE_KEY }}
  MASTER_VITE_GA_ID: ${{secrets.VITE_GA_ID}}
  DEV_VITE_GA_ID: ${{secrets.DEV_VITE_GA_ID}}
  OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
  STAGE: dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Lint
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Build
        run: pnpm run build

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Test
        run: pnpm test -- --coverage
      - name: Test Coverage
        uses: codecov/codecov-action@v3
